version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozon-bank-app  
    ports:
      - "8080:8080"
    environment:
      - STORAGE_TYPE=inmemory
    restart: always   
