version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozon-bank-app  
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
      - POSTGRES_SSLMODE=disable
      - STORAGE_TYPE=postgres
    restart: always   
    depends_on:
      - db
      

  db:
    image: postgres:latest
    container_name: ozon-bank-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql

volumes:
  pg-data:
